config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews
  resources :resources
  resources :users

  root 'resources#index'

  

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  has_many :reviews
  validates :description, :name, presence: true
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :resource
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :resources

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]
  #before_action :not_logged_in, only: [:new]
  before_action :authenticate_user! , except: [:index, :show]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
    @review = Review.new
  end

  # GET /resources/new
  def new
    @resource = Resource.new
    @resource = current_user.resources.build
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)
    @resource = current_user.resources.build(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def not_logged_in
      if not current_user
        redirect_to root_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:name, :description)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
    redirect_to root_path
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :resource_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base



def Destroy
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wynsource</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Rajdhani|Lobster|Orbitron' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/css?family=Raleway:200,100,400" rel="stylesheet" type="text/css" />
  <meta name="author" content="www.twitter.com/cheeriottis">
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="css/core.css">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>

<body>
  <div class="header">
  <h1>Wynsource is
    <span
       class="txt-rotate"
       data-period="2000"
       data-rotate='[ "accesibility.", "simplicity.", "for you." ]'></span>
  </h1>
  <h2>A centralized source created for you.</h2>



 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<% if user_log_in
 <%= link_to "Sign Up", new_user_registration_path %>
 <%= link_to "Sign In", new_user_session_path %>

 <%= link_to "Sign Out", destroy_user_session_path,  :method => :delete %>

<%= yield %>




</div>
</body>
</html>

app/views/resources/_form.html.erb
<div class="container">
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/resources/edit.html.erb
<div class="container">

<div class="edit">
<h1>Editing Resource</h1>

<%= render 'form' %>

<br>
<br>
<%= link_to @resource do %>
<i class="fa fa-search-plus fa-3x"> Show</i>
<% end %>

<%= link_to resources_path do %>
<i class="fa fa-backward fa-3x"> Back</i>
<% end %>


</div>
</div>

app/views/resources/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div class="intro">
<h1>One Solution.</h1>
</div>







<table>

  <thead>
    <tr>
<<<<<<< HEAD

      <!-- <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th> -->

=======
      <th>Resource</th>
      <th>Description</th>
      <th>Collaborator</th>
      <th colspan="3"></th>
>>>>>>> 306ee41c9ae01cf728ff9673148fe4d6c2d65f03
    </tr>
  </thead>


  <tbody>
    <table class="table">

    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.description %></td>
        <td><%= resource.user.email %></td>
        <td><%= link_to 'Show', resource %></td>
<<<<<<< HEAD
        <!-- <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
=======
        <% if resource.user == current_user %>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           <% end %>
>>>>>>> 306ee41c9ae01cf728ff9673148fe4d6c2d65f03
      </tr>
    <% end %>
  </tbody>
</table>
</table>
</div>

<br>


<!-- <%= link_to 'New Resource', new_resource_path %> -->
<%= link_to new_resource_path do  %>
<i class="fa fa-plus fa-4x">    Create New Resource</i>
  <% end %>

app/views/resources/new.html.erb
<div class="container">
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>
</div>

app/views/resources/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<<<<<<< HEAD
<div class="title">
=======


>>>>>>> 306ee41c9ae01cf728ff9673148fe4d6c2d65f03
<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>
</div>
<br>

<div class="review">
<h3>Reviews</h3>
<% @resource.reviews.each do |review| %>
  <p>
    <%= review.comment %>
  </p>
  <div>
    <%= time_ago_in_words review.created_at %> ago
  </div>

<% end %>


<<<<<<< HEAD
=======

>>>>>>> 306ee41c9ae01cf728ff9673148fe4d6c2d65f03
<h3>New Review</h3>

<%= render 'reviews/form' %>

<<<<<<< HEAD
<br>
<br>
<%= link_to edit_resource_path(@resource) do %>
<i class="fa fa-puzzle-piece fa-3x"> Edit</i>
<% end %>


<%= link_to resources_path do %>
<i class="fa fa-backward fa-3x"> Back</i>
<% end %>

</div>
</div>
=======

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>
>>>>>>> 306ee41c9ae01cf728ff9673148fe4d6c2d65f03

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.hidden_field :resource_id, value: @resource.id %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Resource</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.resource %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @review.resource.name %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', @review.resource %>